name: Publish Docker
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: usedandloved/csv-diff-server
          username: ${{ github.actor }}
          # https://github.com/usedandloved/${repo}/settings/secrets/actions
          password: ${{ secrets.GHCR_SECRET }}
          registry: ghcr.io
          default_branch: main
